import Profile1 from "../public/pictures&svgs/chats-svgs/mobile-testing-and-group-discussion.png";
import Profile2 from "../public/pictures&svgs/chats-svgs/concept-of-seo-ranking.png";
import Profile3 from "../public/pictures&svgs/chats-svgs/developer-team.png";
import Profile4 from "../public/pictures&svgs/chats-svgs/teamwork.png";
import Profile5 from "../public/pictures&svgs/chats-svgs/team-building-importance-in-business-success.png";

export const chatsData = {
  projectid: {
    title: "Website Redesign",
    profile: Profile5,
    projectId: "proj-123",
    newMessage: 1,
    chats: [
      {
        id: "chat-1",
        type: "message",
        name: "Yusuf Adeleke",
        userId: "BK456",
        message: "Hey everyone, we have a team outing next Friday! Just a reminder, our project deadline is approaching. Make sure everything's on track.",
        time: "2023-08-25T10:00:00Z",
        image: "",
      },
      {
        id: "chat-2",
        type: "message",
        name: "Alice Johnson",
        userId: "ej488",
        message: "Sure thing! Let's make sure all tasks are on schedule.",
        time: "2023-08-25T11:30:00Z",
        image: "",
      },
      {
        id: "chat-3",
        type: "message",
        name: "Yusuf Adeleke",
        message: "Hey everyone, we have a team outing next Friday! Just a reminder, our project deadline is approaching. Make sure everything's on track.",
        time: "2023-08-25 10:00 ",
        image: "",
        userId: "BK456",
      },
      {
        id: "chat-4",
        type: "message",
        name: "Yusuf Adeleke",
        message: "hahaha.",
        time: "2023-08-25 10:00 ",
        image: "",
        userId: "BK456",
      },
      {
        id: "se-123-1",
        type: "message",
        name: "Yusuf Adeleke",
        message: "Hey everyone, we have a team outing next Friday! Just a reminder, our project deadline is approaching. Make sure everything's on track.",
        time: "2023-08-25 10:00 ",
        image: "",
        userId: "BK456",
      },
      {
        id: "se-123-2",
        type: "message",
        name: "Bob Marley",
        message: "Sounds exciting, Alice! Can't wait!",
        time: "2023-08-25 10:15",
        image: "",
        userId: "BKty56",
      },
      {
        id: "se-123-3",
        type: "message",
        name: "Charlie",
        message: "I'm not sure if I can make it. I'll let you know by tomorrow.",
        time: "2023-08-25 10:30",
        image: "",
        userId: "BK4g6",
      },
      {
        id: "se-123-4",
        type: "message",
        name: "Yusuf Adeleke",
        message: "No worries, Charlie. Just give us a heads up.",
        time: "2023-08-25 10:45",
        image: "",
        userId: "BK456",
      },
      {
        id: "se-123-5",
        type: "image",
        name: "Yusuf Adeleke",
        message: "",
        time: "2023-08-25 10:45",
        image: Profile2,
        userId: "BK456",
      },
      {
        id: "se-123-6",
        type: "message",
        name: "Eve Becker",
        message: "Hey guys, check out this funny meme I found!",
        time: "2023-08-25 11:00",
        image: "",
        userId: "BK456fvev",
      },
      {
        id: "se-123-7",
        type: "message",
        name: "David Beckham",
        message: "Haha, that's hilarious, Eve!",
        time: "2023-08-25 11:05",
        image: "",
        userId: "BK6",
      },
      {
        id: "se-123-8",
        type: "message",
        name: "David Beckham",
        message: "Haha, Really!",
        time: "2023-08-25 11:05",
        image: "",
        userId: "BK456rr",
      },
      {
        id: "se-123-9",
        type: "message",
        name: "Eve Becker",
        message: "Just a reminder, our project deadline is approaching. Make sure everything's on track.",
        time: "2023-08-25 11:30",
        image: "",
        userId: "BK456gg",
      },
      {
        id: "se-123-10",
        type: "image",
        name: "Yusuf Adeleke",
        message: "",
        time: "2023-08-25 10:45",
        image: Profile4,
        userId: "BK456",
      },
      {
        id: "se-123-11",
        type: "message",
        name: "Bob Marley",
        message: "Got it, Alice. I'm finalizing the presentation for the client.",
        time: "2023-08-25 11:45",
        image: "",
        userId: "BK456",
      },
      {
        id: "se-123-13",
        type: "image",
        name: "Bob Marley",
        message: "That's awesome, Charlie! Looking forward to having you there.",
        time: "2023-08-25 12:15",
        image: Profile3,
        userId: "BK45644",
      },
      {
        id: "se-123-12",
        type: "message",
        name: "Charlie",
        message: "I'm in for the team outing! Count me in!",
        time: "2023-08-25 12:00",
        image: "",
        userId: "BK46",
      },
      {
        id: "se-123-14",
        type: "image",
        name: "Yusuf Adeleke",
        message: "",
        time: "2023-08-25 10:45",
        image: Profile2,
        userId: "BK456",
      },
      {
        id: "se-123-15",
        type: "message",
        name: "Yusuf Adeleke",
        message: "Oops, wrong attachment in my previous message. Please disregard it.",
        time: "2023-08-25 01:00",
        image: "",
        userId: "BK456",
      },
      {
        id: "se-123-16",
        type: "message",
        name: "Eve Becker",
        message: "Hey Alice, no problem. Just send the correct one when you can.",
        time: "2023-08-25  01:15",
        image: "",
        userId: "BKg56",
      },
    ],
  },
  projectId2: {
    title: "Website Enhancement",
    profile: Profile4,
    projectId: "proj-456",
    newMessage: 23,
    chats: [
      {
        id: "chat-1",
        type: "message",
        name: "Yusuf Adeleke",
        userId: "BK456",
        message: "Team, great job on completing the user research phase! Let's keep up the momentum.",
        time: "2023-08-25T10:00:00Z",
        image: "",
      },
      {
        id: "chat-2",
        type: "message",
        name: "Alice Johnson",
        userId: "Bwd456",
        message: "Absolutely, Yusuf! The wireframing process is underway, and we're excited about the enhancements.",
        time: "2023-08-25T11:30:00Z",
        image: "",
      },
      {
        id: "chat-3",
        type: "message",
        name: "Emma Davis",
        userId: "BK656",
        message: "Looking forward to contributing to the design mockups. Let's make this website shine!",
        time: "2023-08-25T14:15:00Z",
        image: "",
      },
    ],
  },
  projectID3: {
    title: "Mobile App Development",
    profile: Profile3,
    projectId: "proj-789",
    newMessage: 0,
    chats: [
      {
        id: "chat-1",
        type: "message",
        name: "Sophia Martinez",
        userId: "Bg456",
        message: "Let's kick off this exciting project with thorough market research. Our insights will drive the app's success!",
        time: "2023-09-01T09:00:00Z",
        image: "",
      },
      {
        id: "chat-2",
        type: "message",
        name: "Liam Johnson",
        userId: "BH456",
        message: "Absolutely, Sophia! Once we have the research done, we can dive into crafting an exceptional user experience.",
        time: "2023-09-01T10:30:00Z",
        image: "",
      },
      {
        id: "chat-3",
        type: "message",
        name: "Yusuf Adeleke",
        userId: "BK456",
        message: "Looking forward to collaborating on the backend development. Let's build a robust app that our users will love!",
        time: "2023-09-01T12:15:00Z",
        image: "",
      },
    ],
  },
  projectId4: {
    title: "Product Launch Campaign",
    profile: Profile2,
    projectId: "proj-101",
    newMessage: 4,
    chats: [
      {
        id: "chat-1",
        type: "message",
        name: "Olivia Green",
        userId: "BK436",
        message: "Let's start refining our campaign strategy. We want this launch to be a hit!",
        time: "2023-09-15T10:00:00Z",
        image: "",
      },
      {
        id: "chat-2",
        type: "message",
        name: "Yusuf Adeleke",
        userId: "BK456",
        message: "Absolutely, Olivia! Once the strategy is solid, we'll create compelling content to engage our audience.",
        time: "2023-09-15T11:30:00Z",
        image: "",
      },
      {
        id: "chat-3",
        type: "message",
        name: "Sophie Anderson",
        userId: "CF456",
        message: "Looking forward to designing eye-catching collateral that brings our campaign to life!",
        time: "2023-09-15T13:15:00Z",
        image: "",
      },
    ],
  },
  projectId5: {
    title: "Innovation Project",
    profile: Profile1,
    projectId: "proj-202",
    newMessage: 0,
    chats: [
      {
        id: "chat-1",
        type: "message",
        name: "Daniel Clark",
        userId: "BN456",
        message: "Let's dig deep into market analysis to uncover opportunities for our innovative project.",
        time: "2023-10-01T09:00:00Z",
        image: "",
      },
      {
        id: "chat-2",
        type: "message",
        name: "Emily Smith",
        userId: "BK996",
        message: "Absolutely, Daniel! Once we understand the market, we can begin crafting a cutting-edge concept.",
        time: "2023-10-01T10:30:00Z",
        image: "",
      },
      {
        id: "chat-3",
        type: "message",
        name: "Yusuf Adeleke",
        userId: "BK456",
        message: "Looking forward to prototyping and bringing our groundbreaking innovation to life!",
        time: "2023-10-01T12:15:00Z",
        image: "",
      },
    ],
  },
};
